Add navbar component
khriztianmoreno/Dreadful-Tomatoes-with-React pull request #1
Opened 2022-07-14 03:04 UTC by JuCaMoBa

#### [Add feature navbar] Hola Cristian agregue el componente navbar de la aplicación

2022-07-14 13:28 UTC, khriztianmoreno requested changes

2022-07-14 13:28 UTC, khriztianmoreno commented on package.json
> +    "sass": "^1.53.0"
Esta dependencia no se lleva a produccion por lo tanto debe ir en `devDependencies`

2022-07-14 13:28 UTC, khriztianmoreno commented on src/styles/landingpage.sass
> +body
Se utiliza mejor la extension `.scss` esta version sass no es tan igual a css entonces genera mucha confusion en los equipos, trabaja con la extension `.scss` y conoce las diferencias entre una y otra

2022-07-14 13:28 UTC, khriztianmoreno commented on src/pages/Landingpage.js
> +import Navbar from "./components/Navbar";
Recuerdan siempre programar en bloques.

1. Primero van las dependencias de `node_modules`
2. Un salto de linea
3. Mis componentes
4. Salto de linea
5. Archivos de imagenes o estilos

2022-07-15 15:11 UTC, JuCaMoBa commented on package.json
> -    "react-dom": "^18.0.0"
Ok perfecto

2022-07-15 15:11 UTC, JuCaMoBa commented on src/pages/Landingpage.js
> +import Navbar from "./components/Navbar";
Entendido

2022-07-15 15:11 UTC, JuCaMoBa commented on src/styles/landingpage.sass
> +body
Ok perfecto

2022-07-15 15:20 UTC, JuCaMoBa commented on src/styles/landingpage.sass
> +body
Cambios realizados

2022-07-15 15:20 UTC, JuCaMoBa commented on package.json
> +    "sass": "^1.53.0"
Cambios realizados

2022-07-15 15:22 UTC, JuCaMoBa commented on src/pages/Landingpage.js
> +import Navbar from "./components/Navbar";
Cambios realizados

2022-07-15 15:24 UTC, JuCaMoBa commented on package.json
> -    "react-dom": "^18.0.0"
Cambios realizados

2022-07-15 15:26 UTC, JuCaMoBa reviewed
Resolved

2022-07-15 17:53 UTC, JuCaMoBa reviewed
Resolved

2022-07-15 18:58 UTC, khriztianmoreno approved these changes

2022-07-24 00:06 UTC, JuCaMoBa commented
Hola Cristian agregue nuevos features a la App

2024-12-27 17:25 UTC, closed without merging